---
swagger: "2.0"
info:
  description: "API REST apolline-frontend"
  version: "1.0.0"
  title: "API REST apolline-frontend"
  termsOfService: "terms"
  contact:
    name: "Arthur Baldeck"
    url: "https://github.com/Apolline-Lille/apolline-frontend"
host: "apolline.science"
basePath: "/"
schemes:
- "http"
paths:
  /measurements/{campaign}:
    get:
      tags:
      - "apolline.science"
      summary: "Get all the data of the DataBase \"campaign\""
      description: "Return the whole database choosen \"campaign\" in a CSV file"
      operationId: "measurementsCampaignGET"
      produces:
      - "text/csv"
      parameters:
      - name: "campaign"
        in: "path"
        description: "name of the database choosen"
        required: true
        type: "string"
      responses:
        100:
          description: "Waiting for the end of the file creation"
        201:
          description: "return the data CSV file"
        204:
          description: "there is no content in the database you choose"
        400:
          description: "wrong request"
        404:
          description: "Page not found"
        500:
          description: "internal server error"
      x-swagger-router-controller: "ApollineScience"
definitions: {}
